name: Run End to End Test
run-name: Run End to End Test

on: workflow_dispatch
permissions:

   contents: write
   pages: write
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
   id-token: write
concurrency:

   group: pages
   cancel-in-progress: true
jobs:
   run-end-to-end-test:

      runs-on: ubuntu-latest

      steps:

# Allow one concurrent deployment
      -  name: Checkout master branch of the repo

         uses: actions/checkout@v3

      -  name: Setup Selenium Grid (Hub and Nodes)
         run: docker compose -f docker/armseleniumgrid.yml up -d

      -  name: Set up JDK 17
# Runner will run with this OS

         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt
            cache: maven
      -  name: Run EndToEnd Test
         run: mvn test

      -  name: Get Allure history
         uses: actions/checkout@v3

         if: success() || failure()
# Relative path under $GITHUB_WORKSPACE to place the repository branch that was checked out
         with:
            ref: test-report
            path: test-report
      -  name: Generate Allure Report
         uses: simple-elf/allure-report-action@master
# Cache dependencies from pom.xml, reduces run time by only downloading new dependencies
         if: success() || failure()

         id: allure-report
         with:
            allure_results: allure-results
            gh_pages: test-report
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 20
      -  name: Deploy report to Github Pages
# The repo branch to checkout
         if: success() || failure()

         uses: peaceiris/actions-gh-pages@v3
         with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: test-report
            publish_dir: allure-history
      -  name: Latest Report URL
         if: success() || failure()
         run: echo https://SohamQAKrish.github.io/Krish_Automation/${{ github.run_number }}

# ------------------
# ------------------
# Orphaned comments:
# ------------------
# Was at begin of line:65 :# $GITHUB_WORKSPACE is the default working directory on the runner for steps: /home/runner/work/gh-actions/gh-actions
# Was at begin of line:76 :# Orphaned comments:
# Was at begin of line:77 :# ------------------
# Was at begin of line:78 :# Was at begin of line:65 :# Note that after this workflow, `pages-build-deployment` workflow controlled by GitHub still has to complete before the latest reports are published to GitHub Pages