# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "ManagerPlus/mplus_automation"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "ManagerPlus"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "managerplus_mplusuiautomation"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  Composition:
    title: "Run Selenium Tests"
    type: composition
    arguments:
      composition:
        version: '3'
        services:
          hub:
            image: selenium/hub:3.141.59
            ports:
              - "4444:4444"
            environment:
              - HUB_HOST=hub
              - GRID_BROWSER_TIMEOUT=3400
              - GRID_TIMEOUT=3600
          chrome:
            image: selenium/node-chrome:3.141.59
            depends_on:
              - hub
            shm_size: '1gb'
            environment:
              - HUB_HOST=hub
              - GRID_BROWSER_TIMEOUT=3400
              - GRID_TIMEOUT=3600
            ports:
              - "5900:5900"
      composition_candidates:
        automation_scripts:
          image: '${{build}}'
          volumes:
            - '${{CF_VOLUME_NAME}}:${{CF_VOLUME_PATH}}'
          depends_on:
            - chrome
          environment:
            - HUB_HOST=hub
            - GRID_BROWSER_TIMEOUT=3400
            - GRID_TIMEOUT=3600
          command: "/bin/sh -c 'mvn clean test -Dmaven.test.failure.ignore -DxmlPath=src/test/resources 
          -DsuiteXmlFile=LocalTestSuite.xml; pwd;rm -rf /codefresh/volume/allure-results;cp -rf 
          ./allure-results /codefresh/volume/'"
      fail_fast: false

    stage: "test"

  allure-reports:
    title: "Generate Test Report"
    image: codefresh/cf-docker-test-reporting
    working_directory: '${{CF_VOLUME_PATH}}/'
    environment:
      - CF_STORAGE_INTEGRATION=azure-codefreshtestartifacts-blob
      - BUCKET_NAME=codefreshtestartifacts
    stage: "test"