name: Docker YML workflow
 
on:
  push:
    branches:
      - dockerIntegration  # Adjust to your branch name
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
 
      - name: Build Docker Image
        run: |
          docker build -t bateel-automation-demo:latest .  # Tagging the image
 
      - name: Run Tests and Generate Allure Report
        run: |
            docker run --rm -e DISPLAY=:99 bateel-automation-demo:latest /bin/sh -c "mvn clean test -Dmaven.test.failure.ignore -DxmlPath=src/test/resources -DsuiteXmlFile=LocalTestSuite.xml && mvn allure:report"
 
      - name: Save Allure Report to Local Directory
        run: |
          docker cp $(docker create bateel-automation-demo:latest):/usr/share/HamleysAutomation/allure-report ./allure-report
 
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client
 
      - name: Create Allure Reports Directory on Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH key to GitHub secrets
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p 2255 bateel-automation-demo@bateel-automation-demo.magentoprojects.net "mkdir -p ~/allure-reports"
 
      - name: Copy Allure Report to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH key to GitHub secrets
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -P 2255 -r ./allure-report/* bateel-automation-demo@bateel-automation-demo.magentoprojects.net:~/allure-reports
 
      - name: Cleanup
        run: |
          docker rm $(docker ps -aq) || true
