name: CI

on:
  push:
    branches:
      - main
      - '*'

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.8.1'
          distribution: 'adopt'

      - name: Building Maven Project
        run: mvn -f Krish_Automation/pom.xml clean test-compile
        # Adjust the Maven command to specify the path to the pom.xml file

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      selenium_hub:
        image: selenium/hub:3.141.59
        ports:
          - "4444:4444"
    steps:
      - name: Run Selenium Tests
        run: mvn -f Krish_Automation/pom.xml test -Dmaven.test.failure.ignore -DxmlPath=src/test/resources -DsuiteXmlFile=SanityTestSuite.xml
        # Adjust the Maven command to specify the path to the pom.xml file

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install Allure Commandline
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Test Report
        run: |
          allure generate Krish_Automation/allure-results --clean -o Krish_Automation/allure-report
          # Adjust the paths as per your project structure

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Krish_Automation/allure-report
