version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "allure-reports"

jobs:
  clone:
    title: "Cloning repository"
    steps:
      - title: "Cloning repository"
        type: "git-clone"
        repo: "SohamQAKrish/Krish_Automation"
        revision: "${{CF_BRANCH}}"
        stage: "clone"

  build:
    title: "Building Maven Project"
    steps:
      - title: "Building Maven Project"
        type: "freestyle"
        working_directory: "${{clone}}"
        stage: "build"
        arguments:
          command: "mvn clean test-compile"

  Composition:
    title: "Run Selenium Tests"
    steps:
      - title: "Run Selenium Tests"
        type: "composition"
        arguments:
          composition:
            version: '3'
            services:
              hub:
                image: selenium/hub:3.141.59
                ports:
                  - "4444:4444"
                environment:
                  - HUB_HOST=hub
                  - GRID_BROWSER_TIMEOUT=3400
                  - GRID_TIMEOUT=3600
              chrome:
                image: selenium/node-chrome:3.141.59
                depends_on:
                  - hub
                shm_size: '1gb'
                environment:
                  - HUB_HOST=hub
                  - GRID_BROWSER_TIMEOUT=3400
                  - GRID_TIMEOUT=3600
                ports:
                  - "5900:5900"
        stage: "test"

  allure-reports:
    title: "Generate Test Report"
    steps:
      - title: "Generate Test Report"
        type: "freestyle"
        working_directory: '${{CF_VOLUME_PATH}}/'
        stage: "allure-reports"
        image: ""
        environment: []

# Define event triggers
on:
  push:
    branches:
      - main
      - '*'
