name: CI/CD

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Tests and Generate Allure Report
        run: |
          if [ "${{ github.ref }}" == 'refs/heads/main' ]; then
            mvn clean test -DtestSuiteFile=sanitytestsuite.xml
          else
            mvn clean test -DtestSuiteFile=localtestsuite.xml
          fi
          mvn allure:report

      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results --clean -o allure-report-html

      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

      - name: Set Allure HTML report link 
        if: success()
        run: |
          echo "::set-output name=allure_html_report_link::${{ github.server_url }}/SohamQAKrish/Bateel_Automation/tree/${{ github.ref }}/allure-report-html/index.html"
