name: CI/CD

on:
  push:
    branches:
      - main
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main  # Checkout the main branch

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test
          allure generate allure-results --clean -o allure-report-html

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report-html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: allure-report-html
          CLEAN: true
          BASE_BRANCH: main

      - name: Set Allure HTML report link 
        if: success()
        run: |
          echo "::set-output name=allure_html_report_link::https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-report-html"
