name: CI

on:
  push:
    branches:
      - main
      - '*'

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Building Maven Project
        run: mvn clean test-compile

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      selenium_hub:
        image: selenium/hub:3.141.59
        ports:
          - "4444:4444"
    steps:
      - name: Run Selenium Tests
        run: |
          mvn clean test -Dmaven.test.failure.ignore -DxmlPath=src/test/resources -DsuiteXmlFile=LocalTestSuite.xml
          pwd
          rm -rf /codefresh/volume/allure-results
          cp -rf ./allure-results /codefresh/volume/

  allure-reports:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Generate Test Report
        run: echo "Generate Test Report"
