name: CI

on:
  push:
    branches:
      - main
      - '*'

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
      # You may optionally specify additional steps for setting up Git configuration here

  build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Building Maven Project
        run: mvn clean test-compile
      # Additional steps can be added for packaging or other Maven goals if needed

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      selenium_hub:
        image: selenium/hub:3.141.59
        ports:
          - "4444:4444"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Selenium Tests
        run: mvn test -Dmaven.test.failure.ignore -DxmlPath=src/test/resources -DsuiteXmlFile=SanityTestSuite.xml
        # Adjust the Maven command as per your project setup and requirements

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install Allure Commandline
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Test Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
