name: CI/CD

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: development  # Checkout the development branch

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Allure CLI
        run: |
          choco install allure -y
          refreshenv  # Refresh environment variables after installation

      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test
          mvn allure:report

      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results --clean -o allure-report-html
          mv allure-report-html/index.html allure-results

      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-results

      - name: Set Allure HTML report link
        if: success()
        run: |
          echo "::set-output name=allure_html_report_link::https://KashyapDave95.github.io/Krish_Automation/allure-results/index.html"