name: CI/CD

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test
          mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: C:\Users\kashyap.dave\eclipse-workspace\HybridFramework\allure-results

      - name: Display Allure report link
        if: success()
        run: |
            Write-Host "Allure report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"